apiVersion: v1
kind: Service
metadata:
  labels:
    name: mattermost
  name: mattermost 
spec:
  ports:
    - port: 8065
      targetPort: 8065
      name: mattermost
  selector:
    name: mattermost
