apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: pv01
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /nfsvolumes/pv01
    server: localhost
  persistentVolumeReclaimPolicy: Recycle
