apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: pv02
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /nfsvolumes/pv02
    server: localhost
  persistentVolumeReclaimPolicy: Recycle
